variable "ami_id" {
  description = "The AMI ID for the EC2 instances."
  type        = string
}

variable "instance_type" {
  description = "The instance type for worker nodes."
  type        = string
  default     = "t3.medium"
}

variable "key_name" {
  description = "The name of the SSH key pair to use."
  type        = string
}

variable "private_key_path" {
  description = "Path to the private key file for SSH access."
  type        = string
}

variable "subnet_ids" {
  description = "A list of subnet IDs to launch worker nodes in."
  type        = list(string)
}

variable "security_group_id" {
  description = "The ID of the security group for worker nodes."
  type        = string
}

variable "worker_count" {
  description = "The number of worker nodes to create."
  type        = number
  default     = 2
}

variable "cluster_name" {
  description = "The name of the Kubernetes cluster."
  type        = string
}

variable "kubeadm_join_command" {
  description = "The kubeadm join command generated by the master node."
  type        = string
}

variable "kubeconfig_content" {
  description = "The content of the master's admin.conf file."
  type        = string
}

variable "master_public_ip" {
  description = "The public IP of the master node, used for remote-exec."
  type        = string
}

variable "ansible_user" {
  description = "The SSH user for the AMI (e.g., 'ubuntu' for Ubuntu AMIs)."
  type        = string
  default     = "ubuntu"
}